### ISSUE TITLE
Does not work with latest RestSharp

### ISSUE THREAD

**Issue by mbp** [dillenmeister/Trello.NET#69]
Trello.Net depends on RestSharp >= 104.1.0, but if you upgrade RestSharp to 105.2.3, you get the following exception:

```
System.MissingMethodException: Method was not found: 'Void RestSharp.RestClient.set_Authenticator(RestSharp.IAuthenticator)'.
at TrelloNet.Internal.TrelloRestClient.Authenticate(String memberToken)
at TrelloNet.Trello.Authorize(String token)
```

Trello.Net should either restrict its dependency on RestSharp, or upgrade to the latest version.

**Comment by RickardPettersson** [comment]
i got this same problem now when i updated restsharp...
