### ISSUE TITLE
trello.Boards.WithId throws an exception

### ISSUE THREAD

**Issue by epocaspt** [dillenmeister/Trello.NET#82]
Hello,

The code below was working and now it throws an exception:

trello = new Trello(myTrelloAPIKey);
trello.Authorize(myTrelloAuthorizationToken);
currentBoard = trello.Boards.WithId(myTrelloBoardId);

The exception does not have a message and has the following stack trace:
   at TrelloNet.Internal.TrelloRestClient.ThrowIfRequestWasUnsuccessful(IRestRequest request, IRestResponse response)
   at TrelloNet.Internal.TrelloRestClient.Request[T](IRestRequest request)
   at TrelloNet.Internal.Boards.WithId(String boardId)

I've checked and a direct request to:
https://api.trello.com/1/boards/<boardId>?key=<apiKey>&token=<authorizationToken> works as expected.

Can you help me?

Thanks in advance

**Comment by borgesalan** [comment]
You must add this at the beginning:

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
